name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe it.
      placeholder: "I'm frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "Add a method that..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternative solutions or features you've considered
      placeholder: "I considered using... but..."
    validations:
      required: false

  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - "New API method"
        - "Performance improvement"
        - "New country support"
        - "Better error handling"
        - "Documentation improvement"
        - "Developer experience"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe your use case and why this feature would be valuable
      placeholder: "In my app, I need to..."
    validations:
      required: true

  - type: textarea
    id: example_api
    attributes:
      label: Example API (Optional)
      description: If this is an API change, show how you'd like to use it
      placeholder: |
        ```dart
        // Example usage
        final result = PostcodeChecker.validateAndFormat(CountryCode.US, '12345');
        ```
      value: ""
    validations:
      required: false

  - type: dropdown
    id: breaking_change
    attributes:
      label: Breaking Change
      description: Would this require a breaking change to the API?
      options:
        - "No"
        - "Yes"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other information, mockups, or examples
      value: ""
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am willing to help implement this feature
          required: false
